# Generated by Django 3.1.7 on 2021-04-05 10:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description_short', tinymce.models.HTMLField(blank=True, verbose_name='Короткое описание')),
                ('description_long', tinymce.models.HTMLField(blank=True, verbose_name='Длинное описание')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('long', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='places', verbose_name='Картинка')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
