# Generated by Django 3.1.7 on 2021-03-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210323_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='places', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(blank=True, default=1, verbose_name='Позиция'),
        ),
    ]
